package m.falcon.designpattern.createpattern.factory;

import m.falcon.designpattern.createpattern.domain.ship.Ship;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class ShipFactoryTest {

  @DisplayName("BlackPremiumShip should be generated by constructor DI of premium factory")
  @Test
  void createPremiumBlackShip() {
    // given
    Ship premiumBlackShip = new BlackShipFactory(new BlackShipPremiumPartsFactory()).create();

    // when
    premiumBlackShip.moveShip(); // Moved by BlackPremiumWheel
    premiumBlackShip.stopShip(); // Stopped by BlackPremiumAnchor
  }

  @DisplayName("BlackPremiumShip should be generated by constructor DI of premium factory")
  @Test
  void createNormalWhiteShip() {
    // given
    Ship premiumBlackShip = new WhiteShipFactory(new WhiteShipNormalPartsFactory()).create();

    // when
    premiumBlackShip.moveShip(); // Moved by WhiteWheel
    premiumBlackShip.stopShip(); // Stop by WhiteAnchor
  }
}